package com.tts.starsky.apperceive.db.bao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tts.starsky.apperceive.db.bean.chatMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAT_MESSAGE".
*/
public class chatMessageDao extends AbstractDao<chatMessage, Long> {

    public static final String TABLENAME = "CHAT_MESSAGE";

    /**
     * Properties of entity chatMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MessageId = new Property(0, Long.class, "messageId", true, "_id");
        public final static Property UserId = new Property(1, int.class, "userId", false, "USER_ID");
        public final static Property MessageContext = new Property(2, String.class, "MessageContext", false, "MESSAGE_CONTEXT");
        public final static Property Time = new Property(3, String.class, "Time", false, "TIME");
        public final static Property Readed = new Property(4, int.class, "readed", false, "READED");
    }


    public chatMessageDao(DaoConfig config) {
        super(config);
    }
    
    public chatMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAT_MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: messageId
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"MESSAGE_CONTEXT\" TEXT," + // 2: MessageContext
                "\"TIME\" TEXT," + // 3: Time
                "\"READED\" INTEGER NOT NULL );"); // 4: readed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAT_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, chatMessage entity) {
        stmt.clearBindings();
 
        Long messageId = entity.getMessageId();
        if (messageId != null) {
            stmt.bindLong(1, messageId);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String MessageContext = entity.getMessageContext();
        if (MessageContext != null) {
            stmt.bindString(3, MessageContext);
        }
 
        String Time = entity.getTime();
        if (Time != null) {
            stmt.bindString(4, Time);
        }
        stmt.bindLong(5, entity.getReaded());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, chatMessage entity) {
        stmt.clearBindings();
 
        Long messageId = entity.getMessageId();
        if (messageId != null) {
            stmt.bindLong(1, messageId);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String MessageContext = entity.getMessageContext();
        if (MessageContext != null) {
            stmt.bindString(3, MessageContext);
        }
 
        String Time = entity.getTime();
        if (Time != null) {
            stmt.bindString(4, Time);
        }
        stmt.bindLong(5, entity.getReaded());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public chatMessage readEntity(Cursor cursor, int offset) {
        chatMessage entity = new chatMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // messageId
            cursor.getInt(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // MessageContext
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Time
            cursor.getInt(offset + 4) // readed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, chatMessage entity, int offset) {
        entity.setMessageId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getInt(offset + 1));
        entity.setMessageContext(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setReaded(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(chatMessage entity, long rowId) {
        entity.setMessageId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(chatMessage entity) {
        if(entity != null) {
            return entity.getMessageId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(chatMessage entity) {
        return entity.getMessageId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
