package com.tts.starsky.apperceive.db.bao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tts.starsky.apperceive.db.bean.chatMessage;
import com.tts.starsky.apperceive.db.bean.MessageBean;
import com.tts.starsky.apperceive.db.bean.UserBean;
import com.tts.starsky.apperceive.db.bean.UserSelfBean;

import com.tts.starsky.apperceive.db.bao.chatMessageDao;
import com.tts.starsky.apperceive.db.bao.MessageBeanDao;
import com.tts.starsky.apperceive.db.bao.UserBeanDao;
import com.tts.starsky.apperceive.db.bao.UserSelfBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageDaoConfig;
    private final DaoConfig messageBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig userSelfBeanDaoConfig;

    private final chatMessageDao chatMessageDao;
    private final MessageBeanDao messageBeanDao;
    private final UserBeanDao userBeanDao;
    private final UserSelfBeanDao userSelfBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageDaoConfig = daoConfigMap.get(chatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        messageBeanDaoConfig = daoConfigMap.get(MessageBeanDao.class).clone();
        messageBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        userSelfBeanDaoConfig = daoConfigMap.get(UserSelfBeanDao.class).clone();
        userSelfBeanDaoConfig.initIdentityScope(type);

        chatMessageDao = new chatMessageDao(chatMessageDaoConfig, this);
        messageBeanDao = new MessageBeanDao(messageBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        userSelfBeanDao = new UserSelfBeanDao(userSelfBeanDaoConfig, this);

        registerDao(chatMessage.class, chatMessageDao);
        registerDao(MessageBean.class, messageBeanDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(UserSelfBean.class, userSelfBeanDao);
    }
    
    public void clear() {
        chatMessageDaoConfig.clearIdentityScope();
        messageBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        userSelfBeanDaoConfig.clearIdentityScope();
    }

    public chatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

    public MessageBeanDao getMessageBeanDao() {
        return messageBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public UserSelfBeanDao getUserSelfBeanDao() {
        return userSelfBeanDao;
    }

}
